Remove @types/testing-library__jest-dom, add CI GHA
According to Stack Overflow, to handle this error:

    error TS2688: Cannot find type definition file for 'testing-library__jest-dom'.

You need to do this:

    As of Aug 2023, if you are using the latest version of
    @testing-library/jest-dom, all you need to do is remove
    @types/testing-library_jest-dom.